### PR TITLE
✨ update logical cluster version

### PR DESCRIPTION
**Pull request by pradeepnnv**
Update logical cluster version.
Fixes https://github.com/kcp-dev/controller-runtime/issues/18.

### CODE REVIEW

**Comment by ncdc** [comment]
Thanks! You'll also need to update all the `.go` files currently importing `github.com/kcp-dev/logicalcluster` and change it to `github.com/kcp-dev/logicalcluster/v2`

**Comment by ncdc** [comment]
And then please run `go mod tidy` 😄

**Comment by pradeepnnv** [comment]
Updated the PR with the actual code changes now. @ncdc , please review.

**Comment by ncdc** [comment]
Thanks @pradeepnnv, we need to do a bit of housekeeping to create a new branch that matches the current state of kcp main, which is based on Kubernetes v1.24.x. Let me do that first, and then would you mind retargeting that new branch?

**Comment by pradeepnnv** [comment]
Sure. I'll wait for the new branch to be available.

**Comment by ncdc** [comment]
@pradeepnnv so sorry but we ended up needing to pull this change into the 1.24 rebase PR, but we 💯 appreciate you offering to help out. Hopefully you'll find future opportunities!

Replaced by #21

/close

**Pull request closed without merging**
