### PR TITLE
Misc: attempt to reduce carries

### PR DESCRIPTION
**Pull request by sttts**

### CODE REVIEW

**Comment by xrstf** [comment]
Can you describe in one or two sentences what this PR does? You remove some fields like NewAPIReader, I presume those are now upstream or not needed anymore, because of some refactoring?

**Comment by sttts** [comment]
@xrstf tried to minimize the changes. `NewAPIReader` is replaced wth `newClient`. We reuse the private variable (this is the ugly part). Is it worth it? Not sure. Clearly smaller, but also a bit uglier.

**Comment by xrstf** [comment]
> pkg/kcp/wrappers.go:73:70: directive `// nolint:gosec // this is safe` should be written without leading space as `//nolint:gosec // this is safe` (nolintlint)
>	fieldPointer := (*F)(unsafe.Pointer(newInformerField.UnsafeAddr())) // nolint:gosec // this is safe

Doesn't look like a flake.

**Pull request closed without merging**
